### ISSUE TITLE
 ошибка npm i. и npx knex migrate:latest

### ISSUE THREAD

**Issue by lox1337lox** [alexsprokosin/Economy-Simulator-Russia#7]
это моя первая попытка сделать возрождение для себя может я тупой
ошибка npm i
up to date, audited 595 packages in 4s

66 packages are looking for funding
  run `npm fund` for details

10 vulnerabilities (1 moderate, 7 high, 2 critical)

To address issues that do not require attention, run:
  npm audit fix

To address all issues (including breaking changes), run:
  npm audit fix --force

Run `npm audit` for details.

ошибка npx knex migrate:latest
������������ "postgres" �� ������ �������� ����������� (�� ������)
error: ������������ "postgres" �� ������ �������� ����������� (�� ������)
    at Parser.parseErrorMessage (C:\Users\useru\Desktop\Economy-Simulator-Russia-main\ECSorg-main\services\api\node_modules\pg-protocol\dist\parser.js:278:15)
    at Parser.handlePacket (C:\Users\useru\Desktop\Economy-Simulator-Russia-main\ECSorg-main\services\api\node_modules\pg-protocol\dist\parser.js:126:29)
    at Parser.parse (C:\Users\useru\Desktop\Economy-Simulator-Russia-main\ECSorg-main\services\api\node_modules\pg-protocol\dist\parser.js:39:38)
    at Socket.<anonymous> (C:\Users\useru\Desktop\Economy-Simulator-Russia-main\ECSorg-main\services\api\node_modules\pg-protocol\dist\index.js:10:42)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:324:12)
    at readableAddChunk (node:internal/streams/readable:297:9)
    at Readable.push (node:internal/streams/readable:234:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
я хз как решать я тупой

**Comment by iShowVova** [comment]
у овнера либо экзамены либо он помер вероятнее всего гит хаб опять удалил файлы у меня такое было

**Comment by lox1337lox** [comment]
и чо мне делать

**Comment by lox1337lox** [comment]
> у овнера либо экзамены, либо он помер скорее всего всего гит хаб опять удалил файлы у меня такое было

**Comment by dearnek20** [comment]
файлы можно установить с других источников

**Comment by dearnek20** [comment]
https://github.com/ccr0/economy-simulator можете здесь скачать полный исходник но там надо не которые файлы кто найдет или кто не может найти мне напишите

**Comment by iShowVova** [comment]
@dearnek20 сначала проверь исходник а как он неполный и инкструкция на английском ну кароч он не рабочий

**Comment by alexsprokosin** [comment]
@lox1337lox ты не включил программу prostgen или не создал базу данных, либо не правильно ввёл данные в config.json
